name: Build and sync docs on push to master

on:
  push:
    branches:
      # This workflow will run every time you push code to the following branch: `master`
      # https://docs.github.com/actions/using-workflows/events-that-trigger-workflows
      - master

jobs:
  rdme-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v3

      - name: Run `openapi` command 🚀
        uses: readmeio/rdme@v8
        with:
          rdme: openapi defs/asana_oas.yaml --key=${{ secrets.README_API_KEY }} --id=638e5f87d840f80025e80c75
