name: Build and sync docs on PR merge or pushes to master branch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  rdme-openapi-pr:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo 📚
        uses: actions/checkout@v4
      - name: Run `openapi` command 🚀
        uses: readmeio/rdme@v8
        with:
          rdme: openapi defs/asana_oas.yaml --key=${{ secrets.README_API_KEY }} --id=64a8a031f326ee000e3a92f3
